#!/usr/bin/env bash
# Install nginx web server


sudo apt-get -y update
sudo apt-get -y install nginx
touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo service nginx restart
