#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '30i \\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}
' /etc/nginx/sites-available/default 
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo service nginx start 
