#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt update
sudo apt-get install haproxy=2.8.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "
frontend http
  bind *:80
  mode http
 
default_backend web-backend

backend web-backend
   balance roundrobin
   server 196891-web-01 54.210.88.27:80 check
   server 196891-web-02 52.91.117.155:80 check
" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
