#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2.
i=1
while [ !SIGINT ]
do
	echo "To infinity and beyond"
	sleep 2
	(( i++ ))
done
