#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely, unless killed.
# In between each iteration of the loop, add a sleep 2.
i=1
while [ ! "kill" ]
do
        echo "To infinity and beyond"
        sleep 2
        (( i++ ))
done
