#!/usr/bin/env bash
# This script displays the content of a file. It should only display:
# username
# user id
# Home directory path for the user
while read
do
	cut -d  ':' -f1,4,6
done < "/etc/passwd"
