#!/usr/bin/env bash
# This script check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
file=school
if [ -e "$file" ] ; then
	echo "$file file exists"
	if [ -s "$file" ] ; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f "$file" ] ; then
		echo "$file is a regular file"
	else
		:
	fi
else
	echo "$file file does not exist"
fi	
