#!/usr/bin/env bash
# This script check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
if [ -e "school" ] ; then
	echo "school file exists"
	if [ -s "school" ] ; then
		echo "school file is not empty"
	else
		echo "school file is empty"

	if [ -f "school" ] ; then
		echo "school is a regular file"
else
	echo "school file does not exist"
	fi
	fi
fi	
