#!/usr/bin/env bash
#Run nginx as nginx
#pkill apache2
sudo sed -i "2iuser nginx;\n" /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
